beta_companies = [
    {
      "name": "Google",
      "link": "www.google.com",
      "image": "google.png",
      "country": "US",
      "big_image": "google-big.jpg",
      "interview_difficulty": "72",
      "workers_count": "57",
      "work_life_balance": "80",
      "full_name": "Google",
      "founded": "1998",
      "revenue": "66",
      "headquarters": "Mountain View, CA",
      "program_lang": "java;python;c++;php;go",
      "top_universities": "21%",
      "people_rating": "88",
      "senior_management": "78",
      "culture": "88",
      "benefits": "82",
      "opportunities": "80",
      "remote_friendly": "yes",
      "nationality": "US;IN;GB",
      "entry_schools": "Stanford;US Berkeley;MIT",
      "entry_major": "Computer Science;Computer Engineering;Engineering",
      "entry_degree": "23%",
      "interview_experience": "56",
      "s_soft_engineer": "127",
      "s_soft_senior_engineer": "161",
      "s_product_manager": "148",
      "s_product_senior_manager": "200",
      "s_system_engineer": "110",
      "s_project_manager": "117"
    },
    {
      "name": "Facebook",
      "link": "www.facebook.com",
      "image": "facebook.png",
      "country": "US",
      "big_image": "facebook-big.jpg",
      "interview_difficulty": "64",
      "workers_count": "9.2",
      "work_life_balance": "74",
      "full_name": "Facebook",
      "founded": "2004",
      "revenue": "13",
      "headquarters": "Menlo Park, CA",
      "program_lang": "java;php;python;c++;erlang ",
      "top_universities": "18%",
      "people_rating": "90",
      "senior_management": "84",
      "culture": "90",
      "benefits": "82",
      "opportunities": "86",
      "remote_friendly": "yes",
      "nationality": "US;IN;IT",
      "entry_schools": "Stanford;UC Berkeley;U of Texas",
      "entry_major": "Computer Science;Computer engineering;business management",
      "entry_degree": "29%",
      "interview_experience": "60",
      "s_soft_engineer": "125",
      "s_soft_senior_engineer": "161",
      "s_product_manager": "146",
      "s_product_senior_manager": "143",
      "s_system_engineer": "111",
      "s_project_manager": "108"
    },
    {
      "name": "Microsoft",
      "link": "www.microsoft.com",
      "image": "microsoft.png",
      "country": "US",
      "big_image": "microsoft-big.jpg",
      "interview_difficulty": "64",
      "workers_count": "120",
      "work_life_balance": "72",
      "full_name": "Microsoft Corporation",
      "founded": "1975",
      "revenue": "94",
      "headquarters": "Redmond, WA",
      "program_lang": "c#;c++;java;php;python  ",
      "top_universities": "11%",
      "people_rating": "78",
      "senior_management": "64",
      "culture": "72",
      "benefits": "80",
      "opportunities": "74",
      "remote_friendly": "yes",
      "nationality": "US;IN;CN",
      "entry_schools": "U. of Washington;Washington State;Western Washington",
      "entry_major": "Computer Science;Computer Engineering;Business Management",
      "entry_degree": "27%",
      "interview_experience": "64",
      "s_soft_engineer": "104",
      "s_soft_senior_engineer": "137",
      "s_product_manager": "116",
      "s_product_senior_manager": "131",
      "s_system_engineer": "103",
      "s_project_manager": "102"
    },
    {
      "name": "Apple",
      "link": "www.apple.com",
      "image": "apple.png",
      "country": "US",
      "big_image": "apple-big.jpg",
      "interview_difficulty": "60",
      "workers_count": "80",
      "work_life_balance": "66",
      "full_name": "Apple",
      "founded": "1976",
      "revenue": "234",
      "headquarters": "Cupertino, CA",
      "program_lang": "java;php;c++;python;ruby",
      "top_universities": "7.9%",
      "people_rating": "80",
      "senior_management": "72",
      "culture": "84",
      "benefits": "82",
      "opportunities": "70",
      "remote_friendly": "yes",
      "nationality": "US;GB;CN",
      "entry_schools": "Stanford;San Jose State;UC Berkeley",
      "entry_major": "computer science;business management;engineering",
      "entry_degree": "20%",
      "interview_experience": "66",
      "s_soft_engineer": "121",
      "s_soft_senior_engineer": "147",
      "s_product_manager": "130",
      "s_product_senior_manager": "170",
      "s_system_engineer": "108",
      "s_project_manager": "110"
    },
    {
      "name": "Uber",
      "link": "www.uber.com",
      "image": "uber.png",
      "country": "US",
      "big_image": "uber-big.jpg",
      "interview_difficulty": "60",
      "workers_count": "2",
      "work_life_balance": "68",
      "full_name": "Uber Technologies",
      "founded": "2010",
      "revenue": "10",
      "headquarters": "San Francisco, CA",
      "program_lang": "python;ruby;java;objective-c",
      "people_rating": "88",
      "senior_management": "82",
      "culture": "86",
      "benefits": "82",
      "opportunities": "88",
      "remote_friendly": "yes",
      "entry_major": "Computer & Information Sciences;Computer Science;Business Management",
      "interview_experience": "50",
      "s_soft_engineer": "115",
      "s_soft_senior_engineer": "149",
      "s_system_engineer": "103"
    },
    {
      "name": "LinkedIn",
      "link": "www.linkedin.com",
      "image": "linkedin.png",
      "country": "US",
      "big_image": "linkedin-big.jpg",
      "interview_difficulty": "62",
      "workers_count": "7",
      "work_life_balance": "82",
      "full_name": "LinkedIn Corporation LAD",
      "founded": "2002",
      "revenue": "2",
      "headquarters": "Mountain View, CA",
      "program_lang": "java;php;python;ruby;c++",
      "top_universities": "9%",
      "people_rating": "88",
      "senior_management": "82",
      "culture": "90",
      "benefits": "86",
      "opportunities": "82",
      "remote_friendly": "yes",
      "nationality": "US;IN;MX",
      "entry_schools": "Stanford;US Berkeley;San Joe State",
      "entry_major": "Computer Science;Business Management;Computer Engineering",
      "entry_degree": "32%",
      "interview_experience": "54",
      "s_soft_engineer": "132",
      "s_soft_senior_engineer": "153",
      "s_product_manager": "136",
      "s_product_senior_manager": "157",
      "s_system_engineer": "128"
    },
    {
      "name": "Amazon",
      "link": "www.amazon.com",
      "image": "amazon.png",
      "country": "US",
      "big_image": "amazon-big.jpg",
      "interview_difficulty": "64",
      "workers_count": "132",
      "work_life_balance": "54",
      "full_name": "Amazon",
      "founded": "1994",
      "revenue": "89",
      "headquarters": "Seattle, WA",
      "program_lang": "java;c++;python;PHP;C#",
      "top_universities": "11.5%",
      "people_rating": "72",
      "senior_management": "58",
      "culture": "64",
      "benefits": "70",
      "opportunities": "72",
      "remote_friendly": "yes",
      "nationality": "US;IN;CN",
      "entry_schools": "U of Washington;Carnegie Mellon;Western Washington",
      "entry_major": "computer science;computer engineering;engineering",
      "entry_degree": "28%",
      "interview_experience": "56",
      "s_soft_engineer": "100",
      "s_soft_senior_engineer": "124",
      "s_product_manager": "117",
      "s_product_senior_manager": "127",
      "s_system_engineer": "97",
      "s_project_manager": "88"
    },
    {
      "name": "Adobe",
      "link": "www.adobe.com",
      "image": "adobe.png",
      "country": "US",
      "big_image": "adobe-big.jpg",
      "interview_difficulty": "64",
      "workers_count": "12",
      "work_life_balance": "80",
      "full_name": "Adobe Systems, Incorporated",
      "founded": "1982",
      "revenue": "4",
      "headquarters": "San Jose, CA",
      "program_lang": "java;python;php;c++;ruby",
      "top_universities": "9%",
      "people_rating": "80",
      "senior_management": "72",
      "culture": "82",
      "benefits": "82",
      "opportunities": "70",
      "remote_friendly": "yes",
      "nationality": "US;IN;GB",
      "entry_schools": "Stanford;US Berkeley;San Joe State",
      "entry_major": "Computer Science;Business Management",
      "entry_degree": "26%",
      "interview_experience": "66",
      "s_soft_engineer": "103",
      "s_soft_senior_engineer": "134",
      "s_product_manager": "133",
      "s_product_senior_manager": "155",
      "s_system_engineer": "125",
      "s_project_manager": "100"
    },
    {
      "name": "Intel",
      "link": "www.intel.com",
      "image": "intel.png",
      "country": "US",
      "big_image": "intel-big.jpg",
      "interview_difficulty": "60",
      "workers_count": "106",
      "work_life_balance": "70",
      "full_name": "Intel Corporation",
      "founded": "1968",
      "revenue": "55",
      "headquarters": "Santa Clara, CA",
      "program_lang": "c++;java;c#;python",
      "top_universities": "9%",
      "people_rating": "76",
      "senior_management": "62",
      "culture": "74",
      "benefits": "78",
      "opportunities": "70",
      "remote_friendly": "yes",
      "nationality": "US;IL;IN",
      "entry_schools": "Arizona State;Portland State;California State",
      "entry_major": "Electrical Engineering;Engineering;Computer Science",
      "entry_degree": "34%",
      "interview_experience": "71",
      "s_soft_engineer": "105",
      "s_soft_senior_engineer": "117",
      "s_product_manager": "123",
      "s_product_senior_manager": "136",
      "s_system_engineer": "108",
      "s_project_manager": "95"
    },
    {
      "name": "IBM",
      "link": "www.ibm.com",
      "image": "ibm.png",
      "country": "US",
      "big_image": "ibm-big.jpg",
      "interview_difficulty": "46",
      "workers_count": "380",
      "work_life_balance": "68",
      "full_name": "International Business Machines Corporation",
      "founded": "1911",
      "revenue": "93",
      "headquarters": "Armonk, NY",
      "program_lang": "java;c++;php;python",
      "top_universities": "4%",
      "people_rating": "64",
      "senior_management": "54",
      "culture": "64",
      "benefits": "58",
      "opportunities": "64",
      "remote_friendly": "yes",
      "nationality": "US;IN;GB",
      "entry_schools": "Georgia Tech;Penn State",
      "entry_major": "Computer & Information Sciences;Business Management;Engineering",
      "entry_degree": "20%",
      "interview_experience": "68",
      "s_soft_engineer": "86",
      "s_soft_senior_engineer": "119",
      "s_product_manager": "114",
      "s_product_senior_manager": "136",
      "s_system_engineer": "74",
      "s_project_manager": "92"
    },
    {
      "name": "HP",
      "link": "www.hp.com",
      "image": "hp.png",
      "country": "US",
      "big_image": "hp-big.jpg",
      "interview_difficulty": "58",
      "workers_count": "302",
      "work_life_balance": "70",
      "full_name": "Hewlett-Packard",
      "founded": "1939",
      "revenue": "111",
      "headquarters": "Palo Alto, CA",
      "program_lang": "java;c++;c#;python;php",
      "top_universities": "3%",
      "people_rating": "66",
      "senior_management": "54",
      "culture": "68",
      "benefits": "62",
      "opportunities": "60",
      "remote_friendly": "yes",
      "nationality": "US;IN;GB",
      "entry_schools": "Texas A&M;UC Berkeley;U. of Texas",
      "entry_major": "Computer & Information Sciences;Computer Science",
      "entry_degree": "18%",
      "interview_experience": "69",
      "s_soft_engineer": "97",
      "s_soft_senior_engineer": "121",
      "s_product_manager": "115",
      "s_product_senior_manager": "140",
      "s_system_engineer": "89",
      "s_project_manager": "98"
    },
    {
      "name": "Oracle",
      "link": "www.oracle.com",
      "image": "oracle.png",
      "country": "US",
      "big_image": "oracle-big.jpg",
      "interview_difficulty": "60",
      "workers_count": "135",
      "work_life_balance": "74",
      "full_name": "Oracle Corporation",
      "founded": "1977",
      "revenue": "38",
      "headquarters": "Redwood Shores, CA",
      "program_lang": "java;c++;php;python",
      "top_universities": "8%",
      "people_rating": "68",
      "senior_management": "58",
      "culture": "62",
      "benefits": "62",
      "opportunities": "64",
      "remote_friendly": "yes",
      "nationality": "US;IN;GB",
      "entry_schools": "UC Berkeley;San Jose State;U. of Texas",
      "entry_major": "Computer & Information Sciences;Computer Science;Business Management",
      "entry_degree": "25%",
      "interview_experience": "69",
      "s_soft_engineer": "114",
      "s_soft_senior_engineer": "111",
      "s_product_manager": "108",
      "s_product_senior_manager": "120",
      "s_system_engineer": "84",
      "s_project_manager": "104"
    },
    {
      "name": "Netflix",
      "link": "www.netflix.com",
      "image": "netflix.png",
      "country": "US",
      "big_image": "netflix-big.jpg",
      "interview_difficulty": "58",
      "workers_count": "2",
      "work_life_balance": "66",
      "full_name": "Netflix",
      "founded": "1997",
      "revenue": "5",
      "headquarters": "Los Gatos, CA",
      "program_lang": "java;python;php;c++",
      "top_universities": "8%",
      "people_rating": "74",
      "senior_management": "70",
      "culture": "78",
      "benefits": "86",
      "opportunities": "68",
      "remote_friendly": "yes",
      "nationality": "US;BR;GB",
      "entry_schools": "San Jose State;Stanford;US Berkeley",
      "entry_major": "Computer & Information Sciences;Computer Science;Business Management",
      "entry_degree": "24%",
      "interview_experience": "36",
      "s_soft_engineer": "141",
      "s_soft_senior_engineer": "208",
      "s_product_manager": "124"
    },
    {
      "name": "Hulu",
      "link": "www.hulu.com",
      "image": "hulu.png",
      "country": "US",
      "big_image": "hulu-big.jpg",
      "interview_difficulty": "66",
      "workers_count": "2",
      "work_life_balance": "64",
      "full_name": "Hulu",
      "founded": "2007",
      "revenue": "1",
      "headquarters": "Santa Monica, CA",
      "program_lang": "php;python;java;c++",
      "top_universities": "18%",
      "people_rating": "68",
      "senior_management": "58",
      "culture": "74",
      "benefits": "70",
      "opportunities": "60",
      "remote_friendly": "yes",
      "nationality": "US;BR;IN",
      "entry_schools": "UCLA;USC;UC Invine",
      "entry_major": "Communication/Journalism;Computer & Information Sciences;Computer Science",
      "entry_degree": "18%",
      "interview_experience": "55",
      "s_soft_engineer": "116",
      "s_soft_senior_engineer": "167",
      "s_product_manager": "116",
      "s_system_engineer": "89"
    },
    {
      "name": "Yahoo!",
      "link": "www.yahoo.com",
      "image": "yahoo.png",
      "country": "US",
      "big_image": "yahoo-big.jpg",
      "interview_difficulty": "60",
      "workers_count": "12",
      "work_life_balance": "72",
      "full_name": "Yahoo",
      "founded": "1994",
      "revenue": "5",
      "headquarters": "Sunnyvale, CA",
      "program_lang": "java;php;python;c++",
      "top_universities": "9%",
      "people_rating": "70",
      "senior_management": "56",
      "culture": "72",
      "benefits": "74",
      "opportunities": "64",
      "remote_friendly": "yes",
      "nationality": "US;IN",
      "entry_schools": "San Jose State;USC;US Berkeley",
      "entry_major": "Computer & Information Sciences;Computer Science;Business Management",
      "entry_degree": "27%",
      "interview_experience": "56",
      "s_soft_engineer": "118",
      "s_soft_senior_engineer": "134",
      "s_product_manager": "121",
      "s_product_senior_manager": "144",
      "s_system_engineer": "105",
      "s_project_manager": "102"
    },
    {
      "name": "AOL",
      "link": "corp.aol.com",
      "image": "aol.png",
      "country": "US",
      "big_image": "aol-big.jpg",
      "interview_difficulty": "60",
      "workers_count": "5",
      "work_life_balance": "76",
      "full_name": "AOL",
      "founded": "1985",
      "revenue": "2",
      "headquarters": "New York, NY",
      "program_lang": "java;php;python",
      "people_rating": "72",
      "senior_management": "62",
      "culture": "76",
      "benefits": "76",
      "opportunities": "64",
      "remote_friendly": "yes",
      "nationality": "US;IN;BR",
      "entry_schools": "George Mason;U. of Maryland;NYU",
      "entry_major": "Business Management;Computer & Information Sciences;Computer Science",
      "entry_degree": "16%",
      "interview_experience": "58",
      "s_soft_engineer": "102",
      "s_soft_senior_engineer": "117",
      "s_product_manager": "100",
      "s_product_senior_manager": "115",
      "s_system_engineer": "95",
      "s_project_manager": "89"
    },
    {
      "name": "Dell",
      "link": "www.dell.com",
      "image": "dell.png",
      "country": "US",
      "big_image": "dell-big.jpg",
      "interview_difficulty": "58",
      "workers_count": "108",
      "work_life_balance": "74",
      "full_name": "Dell",
      "founded": "1984",
      "revenue": "59",
      "headquarters": "Round Rock, TX",
      "program_lang": "java;c#;php;c++",
      "top_universities": "6%",
      "people_rating": "70",
      "senior_management": "58",
      "culture": "70",
      "benefits": "66",
      "opportunities": "64",
      "remote_friendly": "yes",
      "nationality": "US;IN;BR",
      "entry_schools": "U. of Texas;Texas State;Texas Tech",
      "entry_major": "Business Management;Computer & Information Sciences;Computer Science",
      "entry_degree": "18%",
      "interview_experience": "68",
      "s_soft_engineer": "90",
      "s_soft_senior_engineer": "117",
      "s_product_manager": "109",
      "s_product_senior_manager": "133",
      "s_system_engineer": "99",
      "s_project_manager": "95"
    },
    {
      "name": "SAP",
      "link": "go.sap.com",
      "image": "sap.png",
      "country": "DE",
      "big_image": "sap-big.jpg",
      "interview_difficulty": "58",
      "workers_count": "74",
      "work_life_balance": "76",
      "full_name": "SAP SE",
      "founded": "1972",
      "revenue": "18",
      "headquarters": "Walldorf, Germany",
      "program_lang": "java;c++;php",
      "top_universities": "4%",
      "people_rating": "78",
      "senior_management": "66",
      "culture": "78",
      "benefits": "78",
      "opportunities": "70",
      "remote_friendly": "yes",
      "nationality": "DE;US;IN",
      "entry_schools": "Penn State;San Jose State;U. of Phoenix",
      "entry_major": "Business Management;Computer & Information Sciences",
      "entry_degree": "28%",
      "interview_experience": "75",
      "s_soft_engineer": "93",
      "s_soft_senior_engineer": "122",
      "s_product_manager": "125",
      "s_product_senior_manager": "137",
      "s_project_manager": "114"
    },
    {
      "name": "Red Hat",
      "link": "www.redhat.com",
      "image": "redhat.png",
      "country": "US",
      "big_image": "redhat-big.jpg",
      "interview_difficulty": "62",
      "workers_count": "8",
      "work_life_balance": "80",
      "full_name": "Red Hat",
      "founded": "1993",
      "revenue": "1.5",
      "headquarters": "Raleigh, NC",
      "program_lang": "java;python;ruby;php",
      "top_universities": "3%",
      "people_rating": "82",
      "senior_management": "72",
      "culture": "84",
      "benefits": "74",
      "opportunities": "78",
      "remote_friendly": "yes",
      "nationality": "US;IN;CZ",
      "entry_schools": "San Jose State;UC Berkeley;Stanford",
      "entry_major": "Computer & Information Sciences;Computer Science;Business Management",
      "entry_degree": "26%",
      "interview_experience": "66",
      "s_soft_engineer": "86",
      "s_soft_senior_engineer": "109",
      "s_project_manager": "67"
    },
    {
      "name": "VMware",
      "link": "www.vmware.com",
      "image": "vmware.png",
      "country": "US",
      "big_image": "vmware-big.jpg",
      "interview_difficulty": "64",
      "workers_count": "18",
      "work_life_balance": "74",
      "full_name": "Vmware",
      "founded": "1998",
      "revenue": "6",
      "headquarters": "Palo Alto, CA",
      "program_lang": "java;python;php",
      "top_universities": "6%",
      "people_rating": "78",
      "senior_management": "66",
      "culture": "78",
      "benefits": "80",
      "opportunities": "70",
      "remote_friendly": "yes",
      "nationality": "US;IN;CN",
      "entry_schools": "San Jose State;UC Berkeley;Stanford",
      "entry_major": "Computer & Information Sciences;Computer Science;Business Management",
      "entry_degree": "32%",
      "interview_experience": "67",
      "s_soft_engineer": "111",
      "s_soft_senior_engineer": "135",
      "s_product_manager": "128",
      "s_product_senior_manager": "153",
      "s_system_engineer": "116",
      "s_project_manager": "121"
    },
    {
      "name": "Ebay",
      "link": "www.ebayinc.com",
      "image": "ebay.png",
      "country": "US",
      "big_image": "ebay-big.jpg",
      "interview_difficulty": "62",
      "workers_count": "35",
      "work_life_balance": "74",
      "full_name": "eBay",
      "founded": "1995",
      "revenue": "18",
      "headquarters": "San Jose, CA",
      "program_lang": "java;php;python",
      "top_universities": "6%",
      "people_rating": "70",
      "senior_management": "56",
      "culture": "70",
      "benefits": "76",
      "opportunities": "62",
      "remote_friendly": "yes",
      "nationality": "US;CN;IN",
      "entry_schools": "San Jose State;UC Berkeley;Stanford",
      "entry_major": "Computer Science;Business Management",
      "entry_degree": "28%",
      "interview_experience": "56",
      "s_soft_engineer": "102",
      "s_soft_senior_engineer": "119",
      "s_product_manager": "113",
      "s_product_senior_manager": "132",
      "s_system_engineer": "129",
      "s_project_manager": "103"
    },
    {
      "name": "Twitter",
      "link": "about.twitter.com",
      "image": "twitter.png",
      "country": "US",
      "big_image": "twitter-big.jpg",
      "interview_difficulty": "62",
      "workers_count": "4",
      "work_life_balance": "80",
      "full_name": "Twitter",
      "founded": "2006",
      "revenue": "1.5",
      "headquarters": "San Francisco, CA",
      "program_lang": "java;python;ruby",
      "top_universities": "21%",
      "people_rating": "80",
      "senior_management": "70",
      "culture": "80",
      "benefits": "82",
      "opportunities": "74",
      "remote_friendly": "yes",
      "nationality": "US;GB;MX",
      "entry_schools": "Stanford;UC Berkeley;MIT",
      "entry_major": "Computer Science;Business Management;Computer Engineering",
      "entry_degree": "33%",
      "interview_experience": "40",
      "s_soft_engineer": "127",
      "s_soft_senior_engineer": "153",
      "s_product_manager": "145",
      "s_system_engineer": "115",
      "s_project_manager": "75"
    },
    {
      "name": "EA",
      "link": "www.ea.com",
      "image": "ea.png",
      "country": "US",
      "big_image": "ea-big.jpg",
      "interview_difficulty": "56",
      "workers_count": "8",
      "work_life_balance": "70",
      "full_name": "Electronic Arts",
      "founded": "1982",
      "revenue": "4.5",
      "headquarters": "Redwood City, CA",
      "program_lang": "java;python;c++;c#",
      "top_universities": "8%",
      "people_rating": "72",
      "senior_management": "64",
      "culture": "72",
      "benefits": "72",
      "opportunities": "66",
      "remote_friendly": "yes",
      "nationality": "US;CA;IN",
      "entry_schools": "U. of Central Florida;Full Sall University;UC Berkeley",
      "entry_major": "Computer Science;Business Management;Computer Engineering",
      "entry_degree": "14%",
      "interview_experience": "63",
      "s_soft_engineer": "92",
      "s_soft_senior_engineer": "131",
      "s_product_manager": "89",
      "s_product_senior_manager": "118",
      "s_system_engineer": "93",
      "s_project_manager": "79"
    },
    {
      "name": "Zynga",
      "link": "www.zynga.com",
      "image": "zynga.png",
      "country": "US",
      "big_image": "zynga-big.jpg",
      "interview_difficulty": "60",
      "workers_count": "2",
      "work_life_balance": "60",
      "full_name": "Zynga",
      "founded": "2007",
      "revenue": "0.7",
      "headquarters": "San Francisco, CA",
      "program_lang": "java;php;python;ruby",
      "top_universities": "15%",
      "people_rating": "64",
      "senior_management": "48",
      "culture": "60",
      "benefits": "76",
      "opportunities": "64",
      "remote_friendly": "yes",
      "nationality": "US;IN;CN",
      "entry_schools": "UC Berkeley;San Jose State;USC",
      "entry_major": "Computer & Information Sciences;Computer Science;Business Management",
      "entry_degree": "26%",
      "interview_experience": "52",
      "s_soft_engineer": "112",
      "s_soft_senior_engineer": "133",
      "s_product_manager": "124",
      "s_product_senior_manager": "134",
      "s_system_engineer": "100",
      "s_project_manager": "104"
    },
    {
      "name": "Cisco",
      "link": "www.cisco.com",
      "image": "cisco.png",
      "country": "US",
      "big_image": "cisco-big.jpg",
      "interview_difficulty": "60",
      "workers_count": "72",
      "work_life_balance": "78",
      "full_name": "Cisco Systems",
      "founded": "1984",
      "revenue": "49",
      "headquarters": "San Jose, CA",
      "program_lang": "java;python;php;c++",
      "top_universities": "6%",
      "people_rating": "76",
      "senior_management": "64",
      "culture": "74",
      "benefits": "74",
      "opportunities": "68",
      "remote_friendly": "yes",
      "nationality": "US;IN;GB",
      "entry_schools": "San Jose State;Stanford",
      "entry_major": "Computer & Information Sciences;Business Management;Computer Science",
      "entry_degree": "27%",
      "interview_experience": "68",
      "s_soft_engineer": "118",
      "s_soft_senior_engineer": "125",
      "s_product_manager": "143",
      "s_product_senior_manager": "147",
      "s_system_engineer": "120",
      "s_project_manager": "110"
    },
    {
      "name": "Juniper",
      "link": "www.juniper.net",
      "image": "juniper.png",
      "country": "US",
      "big_image": "juniper-big.jpg",
      "interview_difficulty": "62",
      "workers_count": "9",
      "work_life_balance": "76",
      "full_name": "Juniper Networks",
      "founded": "1996",
      "revenue": "4.5",
      "headquarters": " Sunnyvale, CA",
      "program_lang": "java;python;php;c++",
      "top_universities": "6%",
      "people_rating": "74",
      "senior_management": "62",
      "culture": "72",
      "benefits": "78",
      "opportunities": "68",
      "remote_friendly": "yes",
      "nationality": "US;IN;CN",
      "entry_schools": "San Jose State;Santa Clara;USC",
      "entry_major": "Computer & Information Sciences;Computer Science;Business Management",
      "entry_degree": "31%",
      "interview_experience": "64",
      "s_soft_engineer": "125",
      "s_soft_senior_engineer": "131",
      "s_product_manager": "150",
      "s_product_senior_manager": "166",
      "s_system_engineer": "124",
      "s_project_manager": "119"
    },
    {
      "name": "Rackspace",
      "link": "www.rackspace.com",
      "image": "rackspace.png",
      "country": "US",
      "big_image": "rackspace-big.jpg",
      "interview_difficulty": "66",
      "workers_count": "4",
      "work_life_balance": "72",
      "full_name": "Rackspace",
      "founded": "1998",
      "revenue": "2",
      "headquarters": "San Antonio, TX",
      "program_lang": "php;python;java;c#",
      "top_universities": "6%",
      "people_rating": "70",
      "senior_management": "56",
      "culture": "74",
      "benefits": "62",
      "opportunities": "70",
      "remote_friendly": "yes",
      "nationality": "US;GB;AU",
      "entry_schools": "U. of Texas;Texas A&M;Texas State",
      "entry_major": "Computer & Information Sciences;Computer Science;Business Management",
      "entry_degree": "16%",
      "interview_experience": "62",
      "s_soft_engineer": "98",
      "s_soft_senior_engineer": "156",
      "s_product_manager": "123",
      "s_product_senior_manager": "125",
      "s_system_engineer": "85",
      "s_project_manager": "70"
    },
    {
      "name": "Akamai",
      "link": "www.akamai.com",
      "image": "akamai.png",
      "country": "US",
      "big_image": "akamai-big.jpg",
      "interview_difficulty": "64",
      "workers_count": "6",
      "work_life_balance": "78",
      "full_name": "Akamai Technologies",
      "founded": "1998",
      "revenue": "1.5",
      "headquarters": "Cambridge, MA",
      "program_lang": "java;python;php;c++",
      "top_universities": "7%",
      "people_rating": "80",
      "senior_management": "72",
      "culture": "80",
      "benefits": "82",
      "opportunities": "74",
      "remote_friendly": "yes",
      "nationality": "US;IN;GB",
      "entry_schools": "Boston U;MIT;Northeastem",
      "entry_major": "Computer & Information Sciences;Computer Science;Business Management",
      "entry_degree": "30%",
      "interview_experience": "62",
      "s_soft_engineer": "103",
      "s_soft_senior_engineer": "127",
      "s_product_manager": "132",
      "s_product_senior_manager": "159"
    },
    {
      "name": "CA",
      "link": "www.ca.com",
      "image": "ca.png",
      "country": "US",
      "big_image": "ca-big.jpg",
      "interview_difficulty": "60",
      "workers_count": "12",
      "work_life_balance": "74",
      "full_name": "CA Technologies",
      "founded": "1976",
      "revenue": "4.5",
      "headquarters": "New York, NY",
      "program_lang": "java;c++;php",
      "top_universities": "3%",
      "people_rating": "64",
      "senior_management": "54",
      "culture": "66",
      "benefits": "72",
      "opportunities": "58",
      "remote_friendly": "yes",
      "nationality": "US;IN;GB",
      "entry_schools": "U. of Phoenix;Hofstra",
      "entry_major": "Computer & Information Sciences;Computer Science;Business Management",
      "entry_degree": "22%",
      "interview_experience": "67",
      "s_soft_engineer": "86",
      "s_soft_senior_engineer": "110",
      "s_product_manager": "101",
      "s_product_senior_manager": "139",
      "s_project_manager": "95"
    },
    {
      "name": "Trulia",
      "link": "www.trulia.com",
      "image": "trulia.png",
      "country": "US",
      "big_image": "trulia-big.jpg",
      "interview_difficulty": "52",
      "workers_count": "1",
      "work_life_balance": "82",
      "full_name": "Trulia",
      "founded": "2005",
      "revenue": "0.2",
      "headquarters": "San Francisco, CA",
      "program_lang": "php;java;python",
      "top_universities": "9%",
      "people_rating": "76",
      "senior_management": "72",
      "culture": "78",
      "benefits": "82",
      "opportunities": "72",
      "remote_friendly": "yes",
      "nationality": "US;IT;CN",
      "entry_schools": "San Francisco St.;UC Berkeley",
      "entry_major": "Computer Science;Business Management;Business Administration",
      "entry_degree": "21%",
      "interview_experience": "46",
      "s_soft_engineer": "124",
      "s_soft_senior_engineer": "141",
      "s_product_manager": "121",
      "s_product_senior_manager": "124"
    }
  ]
